services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  backend-api:
    build:
      context: .
      dockerfile: backend-api/Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo:27017/mp_writer
      - JWT_SECRET=supersecret
      - PORT=4000
      - APP_ORIGIN=http://localhost:3000
      - DATA_ENCRYPTION_KEY=${DATA_ENCRYPTION_KEY:-}
      # Address lookup provider (getaddress.io)
      - GETADDRESS_API_KEY=${GETADDRESS_API_KEY:-}
      - ADDRESS_DEBUG=${ADDRESS_DEBUG:-}
      # Google OAuth (set these in your local override if needed)
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - GOOGLE_CALLBACK_URL=http://localhost:4000/api/auth/google/callback
      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=gpt-4o-mini
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:4000/api/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      backend-api:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_BACKEND_ORIGIN=http://backend-api:4000
    ports:
      - "3000:3000"

volumes:
  mongo_data:
